### ISSUE TITLE
please add selfhost.de

### ISSUE THREAD

**Issue by sphonk** [ayushsharma82/EasyDDNS#1]
Hi thanks for your cool work, can you please selfhost.de dnydns service? many thanks and regards

**Comment by ayushsharma82** [comment]
Yes. Sure. I will Check and Update on That. Expect Update within 10 Hours.

**Comment by ayushsharma82** [comment]
Well. It took over 2 years.. Sorry for the wait. I forgot this small library 😆

**Comment by ayushsharma82** [comment]
Selfhost.de added
