### ISSUE TITLE
Integration of all-inkl DynDns

### ISSUE THREAD

**Issue by laserir** [ayushsharma82/EasyDDNS#12]
Hey, if possible, please integrate the (in Germany VERY popular) paid DynDns service "all-inkl".

The Update URL reads:
`https://USERNAME:PASSWORD@dyndns.kasserver.com/?myip=000.000.000.000`

where **USERNAME** and **PASSWORD** must be specified by the user. **000.000.000.000** must be replaced with the IP address (accepts IP4 or IP6 format).

**Comment by ayushsharma82** [comment]
Sorry for making you wait. I had a lot of work on my head. 

Added `all-inkl` with next release. 

Thanks for your suggestion! 👍
