### ISSUE TITLE
how to use it.

### ISSUE THREAD

**Issue by ajinkyaw** [ayushsharma82/EasyDDNS#2]
hi , i am working on esp8266 projects, found your library. it is quite interesting.
But i am not be able to use it.
If i install DUCKDNS_client example into esp8266, whats next then. 
how to access it via web browser or android app. 
my code is : 

EasyDDNS.service("duckdns");   
EasyDDNS.client("esp.duckdns.org","1234567");    

i tried to access it in web browser but no response. 
please guide. thanks

**Comment by RudyFiero** [comment]
Did you get an account at DuckDNS?   https://www.duckdns.org/

**Comment by ajinkyaw** [comment]
yes i have it..
but i was trying to use it as on local webserver.

**Comment by ayushsharma82** [comment]
@ajinkyaw  You will have to open the the specific IP Address of your device to Internet for accessing it through internet. These Settings can be found in your Router's admin Panel under "Virtual Servers" category.
