### ISSUE TITLE
Support for OVH

### ISSUE THREAD

**Issue by Hydci** [ayushsharma82/EasyDDNS#23]
Hello,
I would like to request the support for the OVH system the link to update and this `https://www.ovh.com/nic/update?system=dyndns&hostname=$HOST&myip=$CURRENT_IP`

To update it asks for an id and a password currently I use a script and send a curl command like this RES = `curl --user "$LOGIN:$PASSWORD" "https://www.ovh.com/nic/update?system=dyndns&hostname=$HOST&myip=$CURRENT_IP"`
Thank's

**Comment by Servuc** [comment]
Wait project creator for merging my request ;)

**Comment by ayushsharma82** [comment]
Merged :) Thanks for your efforts & Have fun
