### ISSUE TITLE
Compilation errors in EasyDDNS.cpp due to obsolete call to "http.begin"

### ISSUE THREAD

**Issue by zmartins** [ayushsharma82/EasyDDNS#29]
Compilation fails due to syntax errors in lines 38 and 85:

 error: call to 'HTTPClient::begin' declared with attribute error: obsolete API, use ::begin(WiFiClient, 
url)

**Comment by kkeonline** [comment]
See my issue report and edit the lib by that.

**Comment by zmartins** [comment]
Thank you,  **_kkeonline_** !          In fact, I had already made such edition in the code right after reading your issue report despite not having understood its previous title.

**Comment by ayushsharma82** [comment]
Fixed with v1.7.0 release.
