### ISSUE TITLE
ipv4.whatismyipaddress fails

### ISSUE THREAD

**Issue by yang3535** [ayushsharma82/EasyDDNS#30]
According to the whatismyipaddress.com website, they are no longer supporting the API for  ipv4bot.whatismyipaddress.com

**Comment by kkeonline** [comment]
I have work around by create an ip lookup url on my private server to provide ip address instread of whatismyipaddress.com

**Comment by yang3535** [comment]
Thanks for the note.  How does your private server figure out the public IP address?

Meanwhile, I've found that http://ifconfig.me/ip can be substituted directly.

I also found others services that are supposed to just return an ip address, but they return error codes in response to the http.GET().  I don't know enough about the interaction to make then usable.

**Comment by khoih-prog** [comment]
This will be fixed by PR [**Replace deprecated whatismyipaddress.com** #31](https://github.com/ayushsharma82/EasyDDNS/pull/31).

In the mean time, you can try to use the modified [**DDNS_Generic**](https://github.com/khoih-prog/DDNS_Generic), which can support many more boards / shields.

**Comment by ayushsharma82** [comment]
Merged PR #31. Thanks @khoih-prog 

This should be fixed with the v1.8.0 release.
If you use a library manager then please wait for at least 12 hours for the ArduinoIDE and PlatformIO library manager to update their index.

**Comment by kkeonline** [comment]
List of some public IP lookup website in plain text 
http(s)://ifconfig.me/ip
http(s)://api.ipify.org/
http(s)://ident.me/
https://api.my-ip.io/ip
https://ip.seeip.org/
